package t_12.backend.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a block stored in the blockchain ledger table.
 */
@Entity
@Table(name = "blocks")
public class Block {

    /**
     * Lifecycle state for a block as it moves through validation.
     */
    public enum Status {
        PENDING, COMMITTED, INVALID
    }

    // Primary key generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Sequential position of the block in the chain.
    @Column(name = "block_height", nullable = false, unique = true)
    private Integer blockHeight;

    // Hash of the parent block so blocks remain linked.
    @Column(name = "previous_hash", length = 128)
    private String previousHash;

    // Unique hash that identifies this block's contents.
    @Column(name = "block_hash", nullable = false, unique = true, length = 128)
    private String blockHash;

    // Wallet address of the validator that produced the block.
    @Column(name = "validator_address", length = 128)
    private String validatorAddress;

    // Time when the block was created or recorded.
    @Column(name = "timestamp")
    private LocalDateTime timestamp;

    // Number of transactions included in the block.
    @Column(name = "transaction_count", nullable = false)
    private Integer transactionCount;

    // Current validation status persisted as a string value.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    /**
     * Returns the block's database id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the block's database id.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getBlockHeight() {
        return blockHeight;
    }

    public void setBlockHeight(Integer blockHeight) {
        this.blockHeight = blockHeight;
    }

    public String getPreviousHash() {
        return previousHash;
    }

    public void setPreviousHash(String previousHash) {
        this.previousHash = previousHash;
    }

    public String getBlockHash() {
        return blockHash;
    }

    public void setBlockHash(String blockHash) {
        this.blockHash = blockHash;
    }

    public String getValidatorAddress() {
        return validatorAddress;
    }

    public void setValidatorAddress(String validatorAddress) {
        this.validatorAddress = validatorAddress;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public Integer getTransactionCount() {
        return transactionCount;
    }

    public void setTransactionCount(Integer transactionCount) {
        this.transactionCount = transactionCount;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }
}
