package t_12.backend.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Marketplace listing backed by the blockchain application database.
 */
@Entity
@Table(name = "listings")
public class Listing {

    /**
     * Availability state for a marketplace listing.
     */
    public enum Status {
        ACTIVE, SOLD, REMOVED
    }

    // Primary key generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // User id of the seller who owns the listing.
    @Column(name = "seller_id", nullable = false)
    private Integer sellerId;

    // Short title displayed in listing results.
    @Column(nullable = false, length = 255)
    private String title;

    // Longer free-form description of the listing.
    @Column(columnDefinition = "TEXT")
    private String description;

    // Asking price for the item or service.
    @Column(nullable = false, precision = 18, scale = 8)
    private BigDecimal price;

    // Category label used to group listings.
    @Column(length = 100)
    private String category;

    // Current listing status stored as text.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    // Optional image URL shown with the listing.
    @Column(name = "image_url", length = 512)
    private String imageUrl;

    // Creation timestamp for sorting and auditing.
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSellerId() {
        return sellerId;
    }

    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
