package t_12.backend.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a transfer of value between wallets.
 */
@Entity
@Table(name = "transactions")
public class Transaction {

    /**
     * Processing state for a transaction.
     */
    public enum Status {
        PENDING, CONFIRMED, REJECTED
    }

    // Primary key generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Address initiating the transfer. It can be null for system-generated transactions.
    @Column(name = "sender_address", length = 128)
    private String senderAddress;

    // Destination address receiving the funds.
    @Column(name = "receiver_address", nullable = false, length = 128)
    private String receiverAddress;

    // Amount of currency being transferred.
    @Column(nullable = false, precision = 18, scale = 8)
    private BigDecimal amount;

    // Network fee charged for processing the transaction.
    @Column(nullable = false, precision = 18, scale = 8)
    private BigDecimal fee;

    // Sender-specific sequence number used to prevent replay.
    @Column(nullable = false)
    private Integer nonce;

    // Timestamp when the transaction was created.
    @Column(name = "timestamp")
    private LocalDateTime timestamp;

    // Unique hash for the transaction payload.
    @Column(name = "transaction_hash", nullable = false, unique = true, length = 128)
    private String transactionHash;

    // Current processing status stored as text.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    // Optional block id once the transaction has been included in a block.
    @Column(name = "block_id")
    private Integer blockId;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSenderAddress() {
        return senderAddress;
    }

    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    public String getReceiverAddress() {
        return receiverAddress;
    }

    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getFee() {
        return fee;
    }

    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    public Integer getNonce() {
        return nonce;
    }

    public void setNonce(Integer nonce) {
        this.nonce = nonce;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public String getTransactionHash() {
        return transactionHash;
    }

    public void setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Integer getBlockId() {
        return blockId;
    }

    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }
}
