package t_12.backend.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a wallet that participates in validating blocks.
 */
@Entity
@Table(name = "validators")
public class Validator {

    /**
     * Current operational state of the validator.
     */
    public enum Status {
        ACTIVE, INACTIVE, JAILED, UNSTAKING
    }

    // Primary key generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Wallet address that identifies the validator.
    @Column(name = "wallet_address", nullable = false, unique = true, length = 128)
    private String walletAddress;

    // Amount currently staked by the validator.
    @Column(name = "staked_amount", nullable = false, precision = 18, scale = 8)
    private BigDecimal stakedAmount;

    // Current validator status stored as text.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    // Time when the validator first joined the set.
    @Column(name = "joined_at")
    private LocalDateTime joinedAt;

    // Most recent time the validator was selected to produce a block.
    @Column(name = "last_selected_at")
    private LocalDateTime lastSelectedAt;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWalletAddress() {
        return walletAddress;
    }

    public void setWalletAddress(String walletAddress) {
        this.walletAddress = walletAddress;
    }

    public BigDecimal getStakedAmount() {
        return stakedAmount;
    }

    public void setStakedAmount(BigDecimal stakedAmount) {
        this.stakedAmount = stakedAmount;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public LocalDateTime getJoinedAt() {
        return joinedAt;
    }

    public void setJoinedAt(LocalDateTime joinedAt) {
        this.joinedAt = joinedAt;
    }

    public LocalDateTime getLastSelectedAt() {
        return lastSelectedAt;
    }

    public void setLastSelectedAt(LocalDateTime lastSelectedAt) {
        this.lastSelectedAt = lastSelectedAt;
    }
}
