package t_12.backend.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Wallet assigned to a user for blockchain-related operations.
 */
@Entity
@Table(name = "wallets")
public class Wallet {

    // Primary key generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // Owning user's id.
    @Column(name = "user_id", nullable = false)
    private Integer userId;

    // Public wallet address used in transactions.
    @Column(name = "wallet_address", nullable = false, unique = true, length = 128)
    private String walletAddress;

    // Public key associated with the wallet.
    @Column(name = "public_key", nullable = false, unique = true, length = 512)
    private String publicKey;

    // Current wallet balance in platform coins.
    @Column(name = "coin_balance", nullable = false, precision = 18, scale = 8)
    private BigDecimal coinBalance;

    // Time the wallet was created.
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getWalletAddress() {
        return walletAddress;
    }

    public void setWalletAddress(String walletAddress) {
        this.walletAddress = walletAddress;
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public BigDecimal getCoinBalance() {
        return coinBalance;
    }

    public void setCoinBalance(BigDecimal coinBalance) {
        this.coinBalance = coinBalance;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
