stages:
  - validate
  - build
  - test
  - lint

check-required-files:
  stage: validate
  image: alpine:latest
  tags:
    - cs506
  rules:
    - when: always
  script:
    - echo "Checking Sprint 0 deliverables..."
    - test -f README.md
    - test -f SKELETON.md
    - test -f STYLE.md
    - test -f ROLES.md
    - test -f .gitignore
    - test -f LOGO.png
    - test -d RESEARCH
    - echo "All required files present."

build-backend:
  stage: build
  image: eclipse-temurin:21-jdk
  tags:
    - cs506
  script:
    - echo "Building backend..."
    - cd backend
    - chmod +x gradlew
    - ./gradlew build -x test
    - ./gradlew compileTestJava

build-frontend:
  stage: build
  image: node:20-alpine
  tags:
    - cs506
  script:
    - echo "Building frontend..."
    - cd frontend
    - npm install
    - npm run build

test-backend:
  stage: test
  image: eclipse-temurin:21-jdk
  tags:
    - cs506
  script:
    - echo "Testing backend..."
    - cd backend
    - chmod +x gradlew
    - ./gradlew test --info
  artifacts:
    when: on_failure
    paths:
      - backend/build/reports/tests/test/
    expire_in: 1 week

test-frontend:
  stage: test
  image: node:20-alpine
  tags:
    - cs506
  script:
    - echo "Testing frontend..."
    - cd frontend
    - npm install
    - npm test -- --watchAll=false --passWithNoTests --verbose

lint-frontend:
  stage: lint
  image: node:20-alpine
  tags:
    - cs506
  script:
    - echo "Linting frontend..."
    - cd frontend
    - npm install
    - npm run lint
