services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: team12root
      MYSQL_DATABASE: crypto_marketplace
      MYSQL_USER: team12admin
      MYSQL_PASSWORD: team12pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crypto_marketplace
      SPRING_DATASOURCE_USERNAME: team12admin
      SPRING_DATASOURCE_PASSWORD: team12pass
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: 60000 # added per race condition where MySQL would restart, 
                                                         # but Spring tries connection during restart
      SPRING_DATASOURCE_HIKARI_INITIALIZATION-FAIL-TIMEOUT: 60000
      JWT_SECRET: team12jwtsecret2026

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080/api

volumes:
  mysql-data: